### ISSUE TITLE
fake trakt scrobbling?

### ISSUE THREAD

**Issue by AreFinstad** [japanesemediamanager/ShokoClient#162]
set play state on Trakt when you start an episode, you can set Trakt on a timer i think from when you start the episode till when its suppose to end (TVDB time/time of file)

EMBY does this with its external launch (like using the EMBY HTPC Client to externally open MPC)
when you start the file it will tell trakt that you are watching the file even tho MPC does not support scrobbling, only thing that this might be more of a hassle is that it doesnt stop when you close MPC (the trakt state i mean) it will continue saying that you are watching whatever eventho you stopped in mid-episode/movie. ofc this will also add the file as a watched file on Trakt even tho you stopped mid file.

**Comment by jmediamanager** [comment]
I have been working on Trakt for the last week or so.
Auto-stopping/pausing a scrobble is not supported by the v2 API, I was looking towards how I could do scrobbling myself.

Unfortunately it would cause too many issues at the moment.
If the API adds support I will revisit this.

**Comment by AreFinstad** [comment]
yeah, just look at how the EMBY client does it as its one of the few that does external play like JMM, send out a playstate on file startup and let it run like that.

**Comment by jmediamanager** [comment]
I can do the start-up quite easily, but can't guarantee that it will do the pause/stop

**Comment by AreFinstad** [comment]
well i wouldnt really mind, like i stated. EMBY doesnt handle this at all with external play anyway. im kind of used too it. ofc it would be the best if it could.

you could have an undo button show up on play tho. like if you exit out of the episode you can click the undo button and it will set it as unwatched on the server aswell as trakt and other places.

**Comment by AreFinstad** [comment]
closing this as we can do scobbling now and thats is a much much better way of doing this.
doing a write up on all the trakt changes needed to get it up-to-date
