### ISSUE TITLE
Button to remove all empty groups

### ISSUE THREAD

**Issue by da3dsoul** [japanesemediamanager/ShokoClient#326]
After going through and reorganizing, I've found I now have dozens of empty groups that I really don't want to bother deleting one at a time.

**Comment by ElementalCrisis** [comment]
Duplicate of https://github.com/japanesemediamanager/jmmclient/issues/30

**Comment by da3dsoul** [comment]
Oh. I did a search but that didn't show up for some reason. It's mentioned that the group should be deleted on move, but that didn't happen.

**Comment by da3dsoul** [comment]
Oh I see, it was a suggestion that hasn't happened yet. Well +1 to that idea

**Comment by ElementalCrisis** [comment]
I closed the other one, since this is the better idea as it provides both options let's keep this one open.

**Comment by da3dsoul** [comment]
Kk. Yeah, I think it's better to not delete anything while organizing until you're done, so nothing gets accidentally deleted.

**Comment by ElementalCrisis** [comment]
I believe this has been fixed? I no longer have empty groups when deleting or moving series.

**Comment by da3dsoul** [comment]
Indeed
