### ISSUE TITLE
Unable To Manually Updated Episode Watched State

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoClient#453]
When clicking the unwatched icon, I get the following error message. 

![unknown](https://cloud.githubusercontent.com/assets/9443295/18254985/d70c77e6-7358-11e6-8f90-9ef5708249bf.png)

Using a fresh SQLite DB.

**Comment by da3dsoul** [comment]
Fixed, but I am experiencing it wiped on JMMServer restart.

**Comment by ElementalCrisis** [comment]
Just checked, Watched state is saved and correct after restarting JMM Server. Can you double-check with latest master?

**Comment by da3dsoul** [comment]
Always on latest master. I think it's some kind of SQL error. I'll see if I can find some info in logs

**Comment by da3dsoul** [comment]
I'm seeing absolutely no trace as to why this happens. I've been busy with the Nancy stuff...and anti-normalfag protests (life).

**Comment by ElementalCrisis** [comment]
Any update @da3dsoul?

**Comment by da3dsoul** [comment]
I'll close this. I've tracked down the cause for the watched states being wiped
