### ISSUE TITLE
Grouping related series - year filter

### ISSUE THREAD

**Issue by RickDB** [japanesemediamanager/ShokoClient#488]
Issue was reported here: http://forum.team-mediaportal.com/threads/my-anime-3.107475/page-92#post-1199282

**Issue**

If you enable the setting "group related series together" it will not correctly work in combination with the year filter.

**To reproduce**

Example with screenshots in linked topic above.

@da3dsoul any idea on this one?

**Comment by da3dsoul** [comment]
Mhmm. Indeed it sounds like a filter issue. It sounds like it's evaluating the group level, but that should be series level

**Comment by da3dsoul** [comment]
The year filters have issues. I'll rework them.

**Comment by da3dsoul** [comment]
FIxed
