### ISSUE TITLE
DEV/Master - You have both Shoko Desktop and Jmmdesktop installed...

### ISSUE THREAD

**Issue by t0815** [japanesemediamanager/ShokoClient#492]
hi, just tested current master - it seems the Uninstall jmmdesktop function uninstalls ShokoDesktop itself, if you upgrade from jmmdesktop to shoko client. The GUID in registry is the same as JMMDesktop.

![image](https://cloud.githubusercontent.com/assets/10379828/20246986/9d4f302a-a9c2-11e6-8509-050b1956b156.png)

**Comment by da3dsoul** [comment]
@elementalcrisis wasn't this fixed?

**Comment by ElementalCrisis** [comment]
It is, however @t0815 said latest master which means he did not install the latest beta which has the updated GUID's.

**Comment by t0815** [comment]
uninstalled everything completely again und installed latest beta, working now.
