### ISSUE TITLE
Switching Tabs Too Fast Crashes Desktop.

### ISSUE THREAD

**Issue by ElementalCrisis** [japanesemediamanager/ShokoClient#503]
To reproduce, click on Dashboard and then click on Collection in quick succession, sometimes clicking each tab multiple times before clicking the other, both tabs will be selected and your log will file with errors. 

Seems to be related to Collection as can only trigger when using it as one of the tabs. 

[2016-12-29.txt](https://github.com/japanesemediamanager/ShokoClient/files/678280/2016-12-29.txt)

**Comment by RickDB** [comment]
Added locking for tab navigation which will help, probably needs the same in other areas but wondering if this will fix it.

**Comment by hidden4003** [comment]
Fixes it for me.
