### ISSUE TITLE
3.7.0.1 want to migrate even when there is no config files

### ISSUE THREAD

**Issue by bigretromike** [japanesemediamanager/ShokoClient#504]
There is no JMM/Shoko Desktop folder as this machine use server only and still after instalation im asked to run as admin...

If its needed to "migrate" or it want to create folder structure inside programdata?
![121212](https://cloud.githubusercontent.com/assets/6052025/21561351/f4a95364-ce6b-11e6-972c-4ca737fa5eca.jpg)

**Comment by ElementalCrisis** [comment]
We should probably change the message as you need to run Shoko initiall as admin to migrate / set permissions. @da3dsoul or @RickDB correct me if I'm wrong as there have been a ton of changes to this part in the past couple of days.

**Comment by da3dsoul** [comment]
It always needs to be run as admin first. Creating the ProgramData folder and settings.

**Comment by bigretromike** [comment]
So maybe we need update message? can we invoke somehow to force to run as admin at first run ?

**Comment by da3dsoul** [comment]
Nope, there's prolly the intended way, to relaunch and ask for admin, but I don't know how to do that.

**Comment by RickDB** [comment]
Gonna see if we can improve on it, know that TreeSize has found a way to re-launch as admin so has to be some way of doing this :)

**Comment by RickDB** [comment]
Not sure if best solution but tried several methods for either Application.Restart but none worked, it will restart as admin only if:

- Is a fresh install without .json config
- Migration required (old style config / folders)

**Comment by bigretromike** [comment]
That should be fine. Thanks you for patch.
