### ISSUE TITLE
Image path setting missing locale string 

### ISSUE THREAD

**Issue by hidden4003** [japanesemediamanager/ShokoClient#506]
There is a broken resource string value:
![image](https://cloud.githubusercontent.com/assets/197087/21579254/50efe9ec-cfae-11e6-9c49-a43123067a5b.png)

Also when pressing said button and folder doesn't exist nothing happens, no error message and folder doesn't change (which is a good thing). Maybe show an error message in this case.

**Comment by RickDB** [comment]
Added error message if path not found as well so this completes the issue :)
