### ISSUE TITLE
JMM Desktop: Ability to rename single files/series only.

### ISSUE THREAD

**Issue by jmediamanager** [japanesemediamanager/ShokoClient#63]
**Reported by valkyria086, Sep 20, 2013**

Hi leo.
Wouldn't it be nice if the renaming utilities could rename only a certain series and not the whole series related to it? For example i just want to rename season 2 of of this anime and i want to keep the filename for season 1 the same name as i download it. Or only the movie version of it and not the series version of it. Thanks man.

**Comment by da3dsoul** [comment]
Pretty sure this is done

**Comment by ElementalCrisis** [comment]
Not at home, can you check?

**Comment by da3dsoul** [comment]
Yeah, it's done
